controller_list:
  - name: fake_left_gripper_controller
    joints:
      - left_gripper_joint
  - name: fake_right_gripper_controller
    joints:
      - right_gripper_joint
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
initial:  # Define initial robot poses.
  - group: left_gripper
    pose: open
  - group: right_gripper
    pose: open
  - group: left_arm
    pose: default
  - group: right_arm
    pose: default