# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: both_arms
  joint_model_group_pose: default
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 10
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    - left_gripper_joint
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
    - right_gripper_joint
  sim_control_mode: 1 # 0: position, 1: velocity
# MoveIt controller interfaces
controller_list:
  - name: left_arm/scaled_vel_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: left_gripper/gripper_controller
    action_ns: gripper_cmd
    default: true
    type: GripperCommand
    allow_failure: true
    joints:
      - left_gripper_joint
      - left_gripper_mirror_joint
  - name: right_arm/scaled_vel_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: right_gripper/gripper_controller
    action_ns: gripper_cmd
    default: true
    type: GripperCommand
    allow_failure: true
    joints:
      - right_gripper_joint
      - right_gripper_mirror_joint
