left_arm:
  move_group_name: left_arm
  planning_frame: prl_ur5_base # The MoveIt planning frame
  ee_frame_name: left_tool # The name of the end effector link, used to return the EE pose
  robot_link_command_frame: prl_ur5_base # commands must be given in the frame of a robot link
  cartesian_command_in_topic: delta_twist_cmds # Topic for incoming Cartesian twist commands
  joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
  joint_topic: joint_states
  status_topic: status # Publish status to this topic
  command_out_topic: /left_arm/joint_group_pos_controller/command # Publish outgoing commands here
  command_out_type: std_msgs/Float64MultiArray

right_arm:
  move_group_name: right_arm
  planning_frame: prl_ur5_base # The MoveIt planning frame
  ee_frame_name: right_tool # The name of the end effector link, used to return the EE pose
  robot_link_command_frame: prl_ur5_base # commands must be given in the frame of a robot link
  cartesian_command_in_topic: delta_twist_cmds # Topic for incoming Cartesian twist commands
  joint_command_in_topic: delta_joint_cmds # Topic for incoming joint angle commands
  joint_topic: joint_states
  status_topic: status # Publish status to this topic
  command_out_topic: /right_arm/joint_group_pos_controller/command # Publish outgoing commands here
  command_out_type: std_msgs/Float64MultiArray
