<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- Build fixed camera with their support from one file -->
    <xacro:macro name="fixed_cameras" params="parent fixed_cameras_file">
        <xacro:property name="fixed_cameras" value="${load_yaml(fixed_cameras_file)}"/>
        <xacro:fixed_cameras_loop parent="${parent}" cameras="${fixed_cameras}"/>
    </xacro:macro>

    <!-- Reccursive macro to iterate over all the cameras -->
    <xacro:macro name="fixed_cameras_loop" params="parent cameras">
        <xacro:if value="${cameras}">
                <!-- pop first item from list -->
                <xacro:property name="camera" value="${cameras.pop(0)}"/>

                <xacro:fixed_camera parent="${parent}" camera="${camera}"/>

                <!-- recursively call myself -->
                <xacro:fixed_cameras_loop parent="${parent}" cameras="${cameras}"/>
        </xacro:if>
    </xacro:macro>


    <!-- Build one camera with its stand -->
    <xacro:macro name="fixed_camera" params="parent camera">
        <!-- Camera -->
        <link name="camera_${camera['name']}">
            <visual>
                <geometry>
                    <box size="${camera['size']['x']} ${camera['size']['y']} ${camera['size']['z']}" />
                </geometry>
                <material name="purple"><color rgba="0.01 0.32 0.41 1"/></material>
            </visual>
            <collision>
                <geometry>
                    <box size="${camera['size']['x']} ${camera['size']['y']} ${camera['size']['z']}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="camera_${camera['name']}">
                <material>Gazebo/BlueGlow</material>
        </gazebo>
        <joint name="camera_${camera['name']}_fix" type="fixed">
            <parent link = "${parent}"/>
            <child link="camera_${camera['name']}"/>
            <origin xyz="${camera['pose']['x']} ${camera['pose']['y']} ${camera['pose']['z']}" rpy="${camera['pose']['roll']} ${camera['pose']['pitch']} ${camera['pose']['yaw']}"/>
        </joint>

        <!-- Numerical dimensions for the fixtures -->
        <xacro:property name="extrusion_width" value="${0.045 +0.02}"/> <!-- +/-1cm margin on the real size -->
        <xacro:property name="hr_z_pos" value="-0.05625"/> <!-- height at which the horizontal extrusion are fixed to the table -->
        <xacro:property name="sj_height" value="${0.08 + 0.09}"/> <!-- Height of the spherical joint supporting the camera + the angle piece supporting the spherical joint -->
        <xacro:property name="sj_diameter" value="${0.09 +0.015}"/> <!-- Diameter of the spherical joint supporting the camera -->

        <!-- Simple math to change the side of the table to which the fixture is attached-->
        <xacro:if value="${camera['fixture_orientation'] == '+x'}">
            <xacro:property name="hr_len" value="${camera['pose']['x'] - camera['offset']['x']}"/>
            <xacro:property name="hr_x_pos" value="${hr_len/2.}"/>
            <xacro:property name="hr_y_pos" value="${camera['pose']['y'] - camera['offset']['y']}"/>
            <xacro:property name="hr_z_rot" value="0"/>
        </xacro:if>
        <xacro:if value="${camera['fixture_orientation'] == '-x'}">
            <xacro:property name="hr_len" value="${-camera['pose']['x'] + camera['offset']['x']}"/>
            <xacro:property name="hr_x_pos" value="${-hr_len/2.}"/>
            <xacro:property name="hr_y_pos" value="${camera['pose']['y'] - camera['offset']['y']}"/>
            <xacro:property name="hr_z_rot" value="3.1415926"/>
        </xacro:if>
        <xacro:if value="${camera['fixture_orientation'] == '+y'}">
            <xacro:property name="hr_len" value="${camera['pose']['y'] - camera['offset']['y']}"/>
            <xacro:property name="hr_x_pos" value="${camera['pose']['x'] - camera['offset']['x']}"/>
            <xacro:property name="hr_y_pos" value="${hr_len/2.}"/>
            <xacro:property name="hr_z_rot" value="1.570796327"/>
        </xacro:if>
        <xacro:if value="${camera['fixture_orientation'] == '-y'}">
            <xacro:property name="hr_len" value="${-camera['pose']['y'] + camera['offset']['y']}"/>
            <xacro:property name="hr_x_pos" value="${camera['pose']['x'] - camera['offset']['x']}"/>
            <xacro:property name="hr_y_pos" value="${-hr_len/2.}"/>
            <xacro:property name="hr_z_rot" value="-1.570796327"/>
        </xacro:if>

        <xacro:property name="vt_len" value="${camera['pose']['z'] - camera['offset']['z'] - camera['size']['z']/2. - hr_z_pos + extrusion_width}"/>

        <!-- Horizontal extrusion -->
        <link name="hr_${camera['name']}">
            <visual>
                <geometry>
                    <box size="${hr_len} ${extrusion_width} ${extrusion_width}" />
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${hr_len} ${extrusion_width} ${extrusion_width}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="hr_${camera['name']}">
                <material>Gazebo/BlueGlow</material>
        </gazebo>
        <joint name="hr_${camera['name']}_fix" type="fixed">
            <parent link = "${parent}"/>
            <child link="hr_${camera['name']}"/>
            <origin xyz="${hr_x_pos} ${hr_y_pos} ${hr_z_pos - extrusion_width/2.}" rpy="0 0 ${hr_z_rot}"/>
        </joint>

        <!-- Vertical extrusion -->
        <link name="vt_${camera['name']}">
            <visual>
                <geometry>
                    <box size="${extrusion_width} ${extrusion_width} ${vt_len}" />
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${extrusion_width} ${extrusion_width} ${vt_len}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="vt_${camera['name']}">
                <material>Gazebo/BlueGlow</material>
        </gazebo>
        <joint name="vt_${camera['name']}_fix" type="fixed">
            <parent link = "${parent}"/>
            <child link="vt_${camera['name']}"/>
            <origin xyz="${camera['pose']['x'] - camera['offset']['x']} ${camera['pose']['y'] - camera['offset']['y']} ${vt_len/2. + hr_z_pos - extrusion_width}" rpy="0 0 0"/>
        </joint>

        <!-- Spherical joint holding the camera -->
        <link name="sj_${camera['name']}">
            <visual>
                <geometry>
                    <cylinder radius="${sj_diameter/2}" length="${sj_height}"/>
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${sj_diameter/2}" length="${sj_height}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="sj_${camera['name']}">
                <material>Gazebo/BlueGlow</material>
        </gazebo>
        <joint name="sj_${camera['name']}_fix" type="fixed">
            <parent link = "${parent}"/>
            <child link="sj_${camera['name']}"/>
            <origin xyz="${camera['pose']['x']} ${camera['pose']['y']} ${camera['pose']['z'] - camera['size']['z']/2. - sj_height/2.}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

</robot>